In [10]:
import pandas as pd

df = pd.read_excel("Deutsche Politik auf Tik Tok - Eine Sammlung von Martin Fuchs @wahl_beobachter.xlsx", skiprows=1)

df.head()

,Unnamed: 0,Name,Tik Tok-Profil,Partei,aktiv,Anmerkungen
0,NaN,NaN,NaN,NaN,NaN,NaN
1,Regierungen,Bundesministerium für Gesundheit,https://www.tiktok.com/@bmg_bund,CDU,x,Erstes Bundeministerium auf Tik Tok (25.03.2020)
2,NaN,Bundesministerium für Verteidigung,https://www.tiktok.com/@bundeswehrexclusive,CDU,x,Eingestellt am 01.05.2020 ; Kanal für Nachwuch...
3,NaN,Bundeskanzler (Bundespresseamt),https://www.tiktok.com/@bundeskanzler,CDU,x,"Aktiv seit 08.04.2024, Zweitaccount https://ww..."
4,NaN,"Bundesministerium für Familie, Senoiren, Fraue...",https://www.tiktok.com/@jugendministerium,CDU,x,Aktiv seit 26.07.2024

## Make a column with only the profile name

In [11]:
df = df[~df["Tik Tok-Profil"].isna()]#only keep the rows where we have profiles

def extract_name(profile_url:str) -> str:
    name = profile_url.split("@")[-1].rstrip()
    return name

df["profile_name"] = df["Tik Tok-Profil"].apply(extract_name)

df.head(50)

,Unnamed: 0,Name,Tik Tok-Profil,Partei,aktiv,Anmerkungen,profile_name
1,Regierungen,Bundesministerium für Gesundheit,https://www.tiktok.com/@bmg_bund,CDU,x,Erstes Bundeministerium auf Tik Tok (25.03.2020),bmg_bund
2,NaN,Bundesministerium für Verteidigung,https://www.tiktok.com/@bundeswehrexclusive,CDU,x,Eingestellt am 01.05.2020 ; Kanal für Nachwuch...,bundeswehrexclusive
3,NaN,Bundeskanzler (Bundespresseamt),https://www.tiktok.com/@bundeskanzler,CDU,x,"Aktiv seit 08.04.2024, Zweitaccount https://ww...",bundeskanzler
4,NaN,"Bundesministerium für Familie, Senoiren, Fraue...",https://www.tiktok.com/@jugendministerium,CDU,x,Aktiv seit 26.07.2024,jugendministerium
5,NaN,Robert Habeck & das Team BMWK,https://www.tiktok.com/@bmwk_habeck,Grüne,x,"Vizekanzler, aktiv ab 24.04.2024 Account des BMWK",bmwk_habeck
6,NaN,Bundesministerium für Wirtschaft und Energie,https://www.tiktok.com/@wirtschaftspolitik,CDU,x,"Umbenannt nach regierungswechsel, vorher https...",wirtschaftspolitik
7,NaN,Auswärtiges Amt,https://www.tiktok.com/@aussenpolitik,CDU,x,Aktiv seit 08.11.2024,aussenpolitik
8,NaN,Finanzminister Lars Klingbeil,https://www.tiktok.com/@minister.larsklingbeil,SPD,x,Aktiv seit 23.09.2025,minister.larsklingbeil
10,Behörden,Bundeswahlleiterin,https://www.tiktok.com/@wahlleitung_de,NaN,x,Aktiv seit 10.12.2024,wahlleitung_de
12,Landesregierung,"Ministerium für Soziales, Gesundheit, Frauen u...",https://www.tiktok.com/@soziales.saarland,SPD,NaN,Erstes deutsches Landesministerium auf Tik Tok...,soziales.saarland
13,NaN,"Bayerisches Staatsministerium für Wohnen, Bau ...",https://www.tiktok.com/@wirbauenbayern,CSU,x,Zweites deutsches Landesministerium auf Tik To...,wirbauenbayern
14,NaN,Ministerium für Finanzen Baden-Württemberg,https://www.tiktok.com/@finanzenbw,Grüne,x,Baden-Württemberg,finanzenbw
15,NaN,Staatskanzlei Mecklenburg-Vorpommern,https://www.tiktok.com/@staatskanzleimv,SPD,x,Mecklenburg-Vorpommern,staatskanzleimv
16,NaN,Regierungspräsdium Tübingen,https://www.tiktok.com/@regierungspraesidium,CDU,NaN,Baden-Württemberg,regierungspraesidium
17,NaN,Ministerpräsident Rheinland-Pfalz,https://www.tiktok.com/@ministerpraesident.rlp,SPD,x,"Rheinland-Pfalz, aktiv seit Wahl von Alexander...",ministerpraesident.rlp
18,NaN,Regierungsprecher Saarland,https://www.tiktok.com/@regsprecher.saarl,SPD,x,Saarland (Start 26.06.2024),regsprecher.saarl
19,NaN,Ministerium für Bildung und Kultur Saarland,https://www.tiktok.com/@mbksaar,SPD,NaN,Saarland,mbksaar
20,NaN,Jusitzministerin Dr. Kathrin Wahlmann,https://www.tiktok.com/@ministerin.kathri,SPD,NaN,"Niedersachsen, wird vom Ministerium betrieben ...",ministerin.kathri
21,NaN,Bildungsministerium Rheinland-Pfalz,https://www.tiktok.com/@bildung_rlp,SPD,x,Rheinland-Pfalz,bildung_rlp
22,NaN,Staatskanzlei Sachsen-Anhalt,https://www.tiktok.com/@stk_sachsenanhalt,CDU,x,"Sachsen-Anhalt, Start 18.12.2026",stk_sachsenanhalt
23,NaN,"Ministerium für Wissenschaft, Energie, Klimasc...",https://www.tiktok.com/@mwu_lsa,SPD,x,Sachsen-Anhalt,mwu_lsa
24,NaN,Ministerium für Bildung Sachsen-Anhalt,https://www.tiktok.com/@bildungsachsenanhalt,CDU,x,Sachsen-Anhalt,bildungsachsenanhalt
26,Parlamente,Europäisches Parlament,https://www.tiktok.com/@europeanparliament,NaN,x,Start 27.02.2024,europeanparliament
27,NaN,Landtag Rheinland-Pfalz,https://www.tiktok.com/@landtagrheinlandpfalz,NaN,x,Start 12.03.2025,landtagrheinlandpfalz
29,Parteien,CSU,https://www.tiktok.com/@csuauftiktok,CSU,x,"Erster Account eines Bundespartei auf Tik Tok,...",csuauftiktok
30,NaN,connectcdu,https://www.tiktok.com/@connectcdu,CDU,NaN,"Wahlkampfteam der CDU, seit 15.01.2021 kurz vo...",connectcdu
31,NaN,AfD,https://www.tiktok.com/@afd.offiziell,AfD,NaN,"Aktiv seit 10.05.2021, gelöscht 5/2022 von Tik...",afd.offiziell
32,NaN,SPD Perlach-Waldperlach,https://www.tiktok.com/@spd_pwp,SPD,NaN,Erster Account der SPD auf Tik Tok,spd_pwp
33,NaN,SPD Lingen,https://www.tiktok.com/@spdlingen,SPD,NaN,NaN,spdlingen
34,NaN,SPD Berlin,https://www.tiktok.com/@spdberlin,SPD,x,NaN,spdberlin
35,NaN,SPD Baden-Württemberg,https://www.tiktok.com/@spd_bawue,SPD,NaN,NaN,spd_bawue
36,NaN,SPD,https://www.tiktok.com/@deinespd,SPD,x,seit 1/2024 auf Tik Tok,deinespd
37,NaN,SPD NRW,https://www.tiktok.com/@nrwspd,SPD,x,seit 3/2024 bei Tik Tok,nrwspd
38,NaN,SPD Saar,https://www.tiktok.com/@saarspd,SPD,x,Seit 3/2024 bei Tik Tok,saarspd
39,NaN,SPD Niedersachsen,https://www.tiktok.com/@spdniedersachsen,SPD,x,NaN,spdniedersachsen
40,NaN,SPD Hamburg,https://www.tiktok.com/@spd_hamburg,SPD,x,NaN,spd_hamburg
41,NaN,SPD Mecklenburg-Vorpommern,https://www.tiktok.com/@spd.mv,SPD,x,Seit 6/2024 bei Tik Tok,spd.mv
42,NaN,SPD Schleswig-Holstein,https://www.tiktok.com/@spdsh,SPD,x,NaN,spdsh
43,NaN,CDU Deutschlands,https://www.tiktok.com/@insidecdu,CDU,x,seit 2/2024 auf Tik Tok,insidecdu
44,NaN,CDU Nunkirchen,https://www.tiktok.com/@cdununkirchen,CDU,x,Erster Account der CDU auf Tik Tok,cdununkirchen
45,NaN,CDU Rade,https://www.tiktok.com/@cdu_rade,CDU,NaN,NaN,cdu_rade
46,NaN,CDU Hessen,https://www.tiktok.com/@cdu_hessen,CDU,x,NaN,cdu_hessen
47,NaN,CDU Rheinland-Pfalz,https://www.tiktok.com/@cdurlp,CDU,x,NaN,cdurlp
48,NaN,CDU Hamburg,https://www.tiktok.com/@cdu_hamburg,CDU,NaN,NaN,cdu_hamburg
49,NaN,CDU Thüringen,https://www.tiktok.com/@cdu_thueringen,CDU,x,NaN,cdu_thueringen
50,NaN,CDU Sachsen,https://www.tiktok.com/@cdu.sachsen,CDU,x,NaN,cdu.sachsen
51,NaN,CDU Brandenburg,https://www.tiktok.com/@cdubrandenburg,CDU,x,NaN,cdubrandenburg
52,NaN,CDU Mecklenburg-Vorpommern,https://www.tiktok.com/@cdu.mv,CDU,x,NaN,cdu.mv
53,NaN,CDU Baden-Württemberg,https://www.tiktok.com/@cdu_bw,CDU,NaN,NaN,cdu_bw
54,NaN,Die LINKE,https://www.tiktok.com/@die.linke,Linke,x,NaN,die.linke